spring:
  application:
    name: med
  data:
    redis:
      host: 192.168.1.242
  datasource:
    hikari:
      username: root
      password: test123456
    url: "jdbc:mysql://192.168.1.242:3306"
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.242
    port: 5672

tsdb:
  type: influxdb
  influxdb:
    url: "http://192.168.1.242:8086"
    org: 1ddc9721dae42ff4
    bucket: demodata
    token: "d8gfMN7Q85weOROvOIdaz3SVoaWtJFOzeA47r6jL5Ewo44fC5rVCED9MPG0i7L_px0nkSK-TZjd9hsjq1bTKTg=="

mybatis:
  mapper-locations: classpath:mapper/*.xml, classpath:chatbot/mapper/*.xml

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  jwt-secret-key: kajsguioahgkldajdglja
  is-read-cookie: false
  timeout: 1800

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-2197d790754d42baa008433429714ba9
        model-name: qwen-turbo
  open-ai:
    embedding-model:
      base-url: "https://api.siliconflow.cn/v1/"
      api-key: sk-asierdoletwgnpamxrkbgxskrjsclnbsnkgmtlbcdubbyjnv
      model-name: "BAAI/bge-m3"
