spring:
  application:
    name: med
  ai:
    mcp:
      server:
        name: demo-server
        type: async
        instructions: "查询用户的胎心数据评估结果"
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
  data:
    redis:
      host: 192.168.1.242
  datasource:
    hikari:
      username: postgres
      password: test123456
    url: "jdbc:postgresql://192.168.1.242:5432/med?currentSchema=public"
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: 192.168.1.242
    port: 5672

tsdb:
  type: influxdb
  influxdb:
    url: "http://192.168.1.242:8086"
    org: 1ddc9721dae42ff4
    bucket: demodata
    token: "d8gfMN7Q85weOROvOIdaz3SVoaWtJFOzeA47r6jL5Ewo44fC5rVCED9MPG0i7L_px0nkSK-TZjd9hsjq1bTKTg=="

mybatis:
  mapper-locations: classpath:mapper/*.xml

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  jwt-secret-key: kajsguioahgkldajdglja
  is-read-cookie: false
  timeout: 1800