spring:
  application:
    name: med
  data:
    redis:
      host: 192.168.1.242
  datasource:
    hikari:
      username: root
      password: test123456
    url: "jdbc:mysql://192.168.1.242:3306/med"
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.1.242
    port: 5672

influxdb:
  url: "http://192.168.1.242:8086"
  org: 1ddc9721dae42ff4
  bucket: demodata
  token: "d8gfMN7Q85weOROvOIdaz3SVoaWtJFOzeA47r6jL5Ewo44fC5rVCED9MPG0i7L_px0nkSK-TZjd9hsjq1bTKTg=="

mybatis:
  mapper-locations: classpath:mapper/*.xml

sa-token:
  token-name: Authorization
  jwt-secret-key: kajsguioahgkldajdglja
  is-read-cookie: false
  timeout: 1800